LANGUAGES = (
    ('ar', 'Arabic'), 
    ('bn', 'Bengali'), 
    ('bg', 'Bulgarian'), 
    ('ca', 'Catalan'), 
    ('cs', 'Czech'), 
    ('cy', 'Welsh'), 
    ('da', 'Danish'), 
    ('de', 'German'), 
    ('el', 'Greek'), 
    ('en', 'English'), 
    ('es', 'Spanish'), 
    ('et', 'Estonian'), 
    ('eu', 'Basque'), 
    ('fa', 'Persian'), 
    ('fi', 'Finnish'), 
    ('fr', 'French'), 
    ('ga', 'Irish'), 
    ('gl', 'Galician'), 
    ('hu', 'Hungarian'), 
    ('he', 'Hebrew'), 
    ('hi', 'Hindi'), 
    ('hr', 'Croatian'), 
    ('is', 'Icelandic'), 
    ('it', 'Italian'), 
    ('ja', 'Japanese'), 
    ('ka', 'Georgian'), 
    ('ko', 'Korean'), 
    ('km', 'Khmer'), 
    ('kn', 'Kannada'), 
    ('lv', 'Latvian'), 
    ('lt', 'Lithuanian'), 
    ('mk', 'Macedonian'), 
    ('nl', 'Dutch'), 
    ('no', 'Norwegian'), 
    ('pl', 'Polish'), 
    ('pt', 'Portuguese'), 
    ('pt-br', 'Brazilian Portuguese'), 
    ('ro', 'Romanian'), 
    ('ru', 'Russian'), 
    ('sk', 'Slovak'), 
    ('sl', 'Slovenian'), 
    ('sr', 'Serbian'), 
    ('sv', 'Swedish'), 
    ('ta', 'Tamil'), 
    ('te', 'Telugu'), 
    ('th', 'Thai'), 
    ('tr', 'Turkish'), 
    ('uk', 'Ukrainian'), 
    ('zh-cn', 'Simplified Chinese'), 
    ('zh-tw', 'Traditional Chinese'),
)
