LANGUAGES = (
    ('en', 'English'),
    ('de', 'German'),
    ('fi', 'Finnish'),
    ('fr', 'French'),
    ('id', 'Indonesian'),
    ('kr', 'Korean'),
    ('ja', 'Japanese'),
    ('it', 'Italian'),
    ('ru', 'Russian'),
    ('sr', 'Serbian'),
    ('es', 'Spanish'),
    ('tr', 'Turkish'),
    ('zh-cn', 'Chinese'),
)

LANGUAGE_PROGRESS = {
    'de': 99.99,
    'en': 100,
    'es': 63,
    'fi': 83,
    'fr': 99,
    'ru': 99,
    'sr': 59,
    'tr': 77,
    'zh-cn': 36,
    'it': 70,
    'ja': 21,
    'id': 1,
    'kr': 0,
}
