#!/bin/sh
# this is a cron job for askbot that includes all
# commands that need to be run periodically
# please find introduction to cron here:
# http://www.unixgeeks.org/security/newbie/unix/cron-1.html
#
# if you prefer, you can split this file into several

PROJECT_PARENT_DIR=/var/www/vhosts/askbot_site1
PROJECT_DIR_NAME=node2

export PYTHONPATH=$PROJECT_PARENT_DIR
PROJECT_ROOT="$PYTHONPATH/$PROJECT_DIR_NAME"

echo $PROJECT_ROOT

#these are actual commands that are to be run
python $PROJECT_ROOT/manage.py send_email_alerts
#python $PROJECT_ROOT/manage.py once_award_badges 
#python $PROJECT_ROOT/manage.py multi_award_badges
